[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "dervflow"
version = "0.1.0"
description = "High-performance mathematics & quantitative finance library"
readme = "README.md"
requires-python = ">=3.10,<3.15"
license = { text = "Apache-2.0" }
authors = [
    { name = "Soumyadip Sarkar", email = "soumyadip@soumyadipsarkar.com" }
]
keywords = [
    "quantitative-finance",
    "options",
    "derivatives",
    "portfolio",
    "risk",
    "monte-carlo",
    "black-scholes",
    "greeks",
    "var",
    "yield-curve"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Rust",
    "Topic :: Office/Business :: Financial",
    "Topic :: Office/Business :: Financial :: Investment",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = [
    "numpy>=1.21,<3.0",
    "scipy>=1.9",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-benchmark",
    "mypy",
    "black",
    "pre-commit",
]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "myst-parser",
]
examples = [
    "jupyter",
    "matplotlib",
    "pandas",
    "scipy",
    "seaborn",
]

[project.urls]
Homepage = "https://github.com/neuralsorcerer/dervflow"
Repository = "https://github.com/neuralsorcerer/dervflow"
Issues = "https://github.com/neuralsorcerer/dervflow/issues"

[tool.maturin]
python-source = "python"
module-name = "dervflow._dervflow"
features = ["python"]
bindings = "pyo3"
compatibility = "manylinux2014"
strip = true
universal2 = true

[tool.pytest.ini_options]
testpaths = ["tests/python"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "-v",
    "--strict-markers",
]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
    "property: marks tests as property-based tests",
]

[tool.mypy]
python_version = "3.10"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.black]
line-length = 100
target-version = ["py310", "py311", "py312", "py313"]

[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E", "F", "I", "N", "W", "UP"]
