name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-rust-docs:
    name: Build Rust Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Rust docs
        run: cargo doc --no-deps --all-features

      - name: Upload Rust docs
        uses: actions/upload-artifact@v5
        with:
          name: rust-docs
          path: target/doc

  build-python-docs:
    name: Build Python Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          allow-prereleases: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate 2>/dev/null || source .venv/Scripts/activate
          python -m pip install -U "pip>=22.1.2"
          python -m pip install "maturin[patchelf]"
          maturin develop --release
          python -m pip install ".[dev]"
          pip install sphinx sphinx-rtd-theme myst-parser sphinx-autodoc-typehints

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html

      - name: Upload Python docs
        uses: actions/upload-artifact@v5
        with:
          name: python-docs
          path: docs/build/html

  deploy-docs:
    name: Deploy Documentation
    needs: [build-rust-docs, build-python-docs]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: Download Rust docs
        uses: actions/download-artifact@v6
        with:
          name: rust-docs
          path: docs-deploy/rust

      - name: Download Python docs
        uses: actions/download-artifact@v6
        with:
          name: python-docs
          path: docs-deploy/python

      - name: Create index page
        run: |
          cat > docs-deploy/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>DervFlow Documentation</title>
              <meta charset="utf-8">
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
                      max-width: 800px;
                      margin: 50px auto;
                      padding: 20px;
                  }
                  h1 { color: #333; }
                  .links { margin-top: 30px; }
                  .link-box {
                      display: inline-block;
                      padding: 20px 40px;
                      margin: 10px;
                      background: #007bff;
                      color: white;
                      text-decoration: none;
                      border-radius: 5px;
                      font-size: 18px;
                  }
                  .link-box:hover { background: #0056b3; }
              </style>
          </head>
          <body>
              <h1>DervFlow Documentation</h1>
              <p>High-performance quantitative finance library built with Rust and Python.</p>
              <div class="links">
                  <a href="python/index.html" class="link-box">Python API Documentation</a>
                  <a href="rust/dervflow/index.html" class="link-box">Rust API Documentation</a>
              </div>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-deploy
